<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>yodaphone-web-5b51b329-0c43-4f79-bb9e-d5f8f3351b50</UserSecretsId>
    
    <!-- Workaround for dotnet/sdk#54309 on Linux and macOS -->
    <IntermediateOutputPath>obj/$(Configuration)/</IntermediateOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Github.Copilot.SDK" Version="1.0.13-preview.2" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12" />
  </ItemGroup>

</Project>
