<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    
    <!-- Workaround for dotnet/sdk#54309 on Linux and macOS -->
    <IntermediateOutputPath>obj/$(Configuration)/</IntermediateOutputPath>
  </PropertyGroup>

</Project>
